# Generated by Django 5.2.15 on 2026-06-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurej', models.CharField(max_length=100, verbose_name='NUREJ')),
                ('demandante', models.CharField(max_length=255, verbose_name='Demandante')),
                ('demandado', models.CharField(max_length=255, verbose_name='Demandado')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('tipo_proceso', models.CharField(choices=[('Divorcio', 'Divorcio'), ('Asistencia Familiar', 'Asistencia Familiar'), ('Guarda', 'Guarda'), ('Regimen de Visitas', 'Regimen de Visitas'), ('Filiacion', 'Filiacion')], max_length=100, verbose_name='Tipo de Proceso')),
                ('tipo_audiencia', models.CharField(choices=[('Conciliacion', 'Conciliacion'), ('Ratificacion', 'Ratificacion'), ('Seguimiento', 'Seguimiento'), ('Evaluacion', 'Evaluacion'), ('Preliminar', 'Preliminar')], max_length=100, verbose_name='Tipo de Audiencia')),
                ('sala', models.CharField(choices=[('Sala 1', 'Sala 1'), ('Sala 2', 'Sala 2'), ('Sala 3', 'Sala 3'), ('Sala Virtual', 'Sala Virtual')], max_length=100, verbose_name='Sala')),
                ('juez', models.CharField(choices=[('Dra. Jimenez', 'Dra. Jimenez'), ('Dr. Perez', 'Dr. Perez'), ('Dra. Salazar', 'Dra. Salazar'), ('Dr. Quiroga', 'Dr. Quiroga')], max_length=100, verbose_name='Juez')),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('En curso', 'En curso'), ('Concluida', 'Concluida'), ('Suspendida', 'Suspendida'), ('Reprogramada', 'Reprogramada')], default='Programada', max_length=100, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_suspension', models.CharField(blank=True, choices=[('Incomparecencia', 'Incomparecencia'), ('Falta de notificacion', 'Falta de notificacion'), ('Problemas tecnicos', 'Problemas tecnicos'), ('Solicitud de las partes', 'Solicitud de las partes')], max_length=255, null=True, verbose_name='Motivo de Suspension')),
                ('historial', models.TextField(default='[]', verbose_name='Historial')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Audiencia',
                'verbose_name_plural': 'Audiencias',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
